from __future__ import annotations

import builtins
from typing import Any

class dtype: ...

bool: dtype
uint8: dtype
int32: dtype
int64: dtype
float16: dtype
float32: dtype
float64: dtype

class Tensor:
    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> dtype: ...
    def detach(self) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def numpy(self) -> Any: ...
    def item(self) -> builtins.bool | int | float: ...
    def reshape(self, *shape: int | tuple[int, ...]) -> Tensor: ...

def tensor(data: object, dtype: dtype | None = None) -> Tensor: ...
def as_tensor(data: object, dtype: dtype | None = None) -> Tensor: ...
def frombuffer(buffer: object, *, dtype: dtype) -> Tensor: ...
def arange(end: int, *, dtype: dtype | None = None) -> Tensor: ...
