# This file is automatically generated by pyo3_stub_gen
# ruff: noqa

import builtins
import collections.abc
import typing
from typing import TypeAlias, TypedDict
__all__ = [
    "RLMeshException",
    "ProtocolException",
    "EnvironmentException",
    "ACTION_DELTA_POS",
    "ACTION_DELTA_POS_2",
    "ACTION_DELTA_ROT",
    "ACTION_DELTA_ROT_2",
    "ACTION_EEF_POS",
    "ACTION_EEF_POS_2",
    "ACTION_EEF_ROT",
    "ACTION_EEF_ROT_2",
    "ACTION_GRIPPER",
    "ACTION_GRIPPER_2",
    "ACTION_JOINT_POS",
    "ACTION_JOINT_POS_2",
    "ACTION_JOINT_VEL",
    "ARM_2",
    "AdapterPlan",
    "Advisory",
    "BASE",
    "BASE_ANG_VEL",
    "BASE_ROT",
    "BuildInfo",
    "CHANNEL_ORDERS",
    "COMMAND_BASE_VEL",
    "CROP_MODES",
    "DESCRIBE_METADATA_KEY",
    "DESCRIBE_SCHEMA_VERSION",
    "EEF_POS",
    "EEF_POS_2",
    "EEF_ROT",
    "EEF_ROT_2",
    "EEF_WRENCH",
    "EMBODIMENTS",
    "ENV_BRANCH_METADATA_KEY",
    "ENV_METADATA_KEY",
    "ENV_RESET_OPTIONS_KEY",
    "EnvContract",
    "GRIPPER_POS",
    "GRIPPER_POS_2",
    "HEAD",
    "IMAGE_LAYOUTS",
    "IMAGE_PRIMARY",
    "IMAGE_SECONDARY",
    "IMAGE_WRIST",
    "IMAGE_WRIST_2",
    "INSTRUCTION",
    "JOINT_POS",
    "JOINT_VEL",
    "LEFT_ARM",
    "LEFT_LEG",
    "MODEL_METADATA_KEY",
    "PARTS",
    "PrimitiveValue",
    "PyEnvClient",
    "PyEnvServer",
    "PyModel",
    "PyModelClient",
    "PyVectorEnvClient",
    "PyVectorEnvServer",
    "PyVideoWriter",
    "PyViewer",
    "RESAMPLES",
    "RIGHT_ARM",
    "RIGHT_LEG",
    "ROTATION_DIMS",
    "ServeOptions",
    "Space",
    "SpaceSpec",
    "TORSO",
    "Tensor",
    "Value",
    "adapters_join_check",
    "adapters_resolve",
    "adapters_spec_normalize",
    "box_space_spec",
    "build_info",
    "current_workflow_edition",
    "describe_envelope_normalize",
    "dict_space_spec",
    "discrete_space_spec",
    "multi_binary_space_spec",
    "multi_discrete_space_spec",
    "predict_seed",
    "run_cli",
    "sandbox_reap_orphans",
    "sandbox_start_env",
    "sandbox_stop_env",
    "space_spec_from_gym_space",
    "text_space_spec",
    "tuple_space_spec",
    "validate_workflow_edition",
]

PrimitiveValue: TypeAlias = None | bool | int | float | str | bytes
Value: TypeAlias = PrimitiveValue | Tensor | list["Value"] | tuple["Value", ...] | dict[str, "Value"]
ACTION_DELTA_POS: builtins.str
ACTION_DELTA_POS_2: builtins.str
ACTION_DELTA_ROT: builtins.str
ACTION_DELTA_ROT_2: builtins.str
ACTION_EEF_POS: builtins.str
ACTION_EEF_POS_2: builtins.str
ACTION_EEF_ROT: builtins.str
ACTION_EEF_ROT_2: builtins.str
ACTION_GRIPPER: builtins.str
ACTION_GRIPPER_2: builtins.str
ACTION_JOINT_POS: builtins.str
ACTION_JOINT_POS_2: builtins.str
ACTION_JOINT_VEL: builtins.str
ARM_2: builtins.str
BASE: builtins.str
BASE_ANG_VEL: builtins.str
BASE_ROT: builtins.str
CHANNEL_ORDERS: builtins.list[builtins.str]
COMMAND_BASE_VEL: builtins.str
CROP_MODES: builtins.list[builtins.str]
DESCRIBE_METADATA_KEY: builtins.str
DESCRIBE_SCHEMA_VERSION: builtins.int
EEF_POS: builtins.str
EEF_POS_2: builtins.str
EEF_ROT: builtins.str
EEF_ROT_2: builtins.str
EEF_WRENCH: builtins.str
EMBODIMENTS: builtins.list[tuple[builtins.str, builtins.list[builtins.str], builtins.list[builtins.str]]]
ENV_BRANCH_METADATA_KEY: builtins.str
ENV_METADATA_KEY: builtins.str
ENV_RESET_OPTIONS_KEY: builtins.str
GRIPPER_POS: builtins.str
GRIPPER_POS_2: builtins.str
HEAD: builtins.str
IMAGE_LAYOUTS: builtins.list[builtins.str]
IMAGE_PRIMARY: builtins.str
IMAGE_SECONDARY: builtins.str
IMAGE_WRIST: builtins.str
IMAGE_WRIST_2: builtins.str
INSTRUCTION: builtins.str
JOINT_POS: builtins.str
JOINT_VEL: builtins.str
LEFT_ARM: builtins.str
LEFT_LEG: builtins.str
MODEL_METADATA_KEY: builtins.str
PARTS: builtins.list[builtins.str]
RESAMPLES: builtins.list[builtins.str]
RIGHT_ARM: builtins.str
RIGHT_LEG: builtins.str
ROTATION_DIMS: builtins.dict[builtins.str, builtins.int]
TORSO: builtins.str
__version__: builtins.str

__build__: builtins.str

class RLMeshException(builtins.RuntimeError): ...

class ProtocolException(RLMeshException): ...

class EnvironmentException(RLMeshException): ...

ResetInfo: TypeAlias = dict[str, object]

StepInfo: TypeAlias = dict[str, object]

class SandboxRunInfo(TypedDict):
    requested_source: str
    resolved_source: str
    address: str
    container_id: str

class SandboxBuildInfo(TypedDict):
    requested_source: str
    resolved_source: str
    image: str
    alias: str | None
    image_id: str

@typing.final
class AdapterPlan:
    r"""
    A resolved adapter plan handle backed by the `rlmesh-adapters` core.
    """
    def describe(self) -> builtins.str:
        r"""
        Human-readable summary of the resolved transformations.
        """
    def advisories(self) -> builtins.list[Advisory]:
        r"""
        Per-env data-loss / fabrication notes (zero-filled camera, aspect crop):
        the "warn" subset of `describe`, empty when nothing noteworthy happened.
        Each note carries a severity tier (`"info"` / `"caution"`).
        """
    def referenced_obs_keys(self) -> builtins.list[builtins.str]:
        r"""
        The top-level observation keys this adapter reads.
        
        A host wrapper should encode only these before calling
        [`transform_obs`](Self::transform_obs), so an unused — possibly
        unencodable — observation key never aborts a step.
        """
    def custom_inputs(self) -> builtins.list[tuple[builtins.list[builtins.str | builtins.int], builtins.str]]:
        r"""
        `(segments, transform)` pairs for custom-input holes, plan order.
        
        `segments` is the custom leaf's structured placement path: each step is a
        `str` (`Dict` key) or `int` (`Tuple` index), built directly from the
        native `NodePath` — no placement string for the caller to re-parse. An
        empty segment list is the root (a bare-leaf payload).
        """
    def state_layouts(self) -> builtins.list[tuple[builtins.list[builtins.str | builtins.int], builtins.list[builtins.int], builtins.int]]:
        r"""
        `(segments, part_widths, width)` per resolved state input, plan order.
        
        `segments` is the state leaf's structured placement path (as in
        [`custom_inputs`](Self::custom_inputs)), `part_widths` the resolved width
        each declared part contributes in order, and `width` the assembled
        leaf's width (its `pad_to` when it pads). A host-side custom encoding
        reads and writes exactly its own slice of the leaf, whose offset is the
        sum of the widths before it — env-dependent, so it is knowable only
        here, after resolve. A state whose widths are not all statically known
        is omitted (nothing can be addressed inside it).
        """
    def transform_obs(self, raw_obs: typing.Any) -> typing.Any:
        r"""
        Apply the observation plans to a canonical value-tree observation map.
        
        Returns the assembled payload as a neutral Python object (a nested
        dict/list/leaf — the model spec's `InputNode` shape, a Value tree);
        custom inputs are omitted (the caller fills them from the raw host
        observation).
        """
    def history_keys(self) -> builtins.list[builtins.str]:
        r"""
        Canonical placement strings of the inputs that hold per-episode history:
        a frame window, or a part reading the model's previous action.
        
        Empty means an env step that predicts nothing has no state to advance, so
        the caller can skip [`transform_history`](Self::transform_history)
        entirely.
        """
    def history_windows(self) -> builtins.list[tuple[builtins.str, builtins.int, builtins.int]]:
        r"""
        `(key, span, frame_bytes)` per frame window this plan holds per live
        episode — what a caller budgets `num_envs x sum(span x frame_bytes)`
        from before a route runs. `frame_bytes` is `0` when the env's camera
        resolution was not derivable.
        """
    def transform_history(self, raw_obs: typing.Any) -> None:
        r"""
        Advance the frame windows from a raw observation, assembling nothing.
        
        The tick a step that replays a queued action owes its history: the frame
        still happened, so it still goes in the window, and the local step
        counter advances so the replayed action is recorded under its step.
        """
    def reset_history(self) -> None:
        r"""
        Drop the in-process frame windows (and the local step counter) at an
        episode boundary.
        """
    def transform_action(self, raw_action: typing.Any) -> typing.Any:
        r"""
        Apply the action plan to a canonical value-tree model action, recording
        it as the action executed at the step last ticked when a state part
        reads the previous action (the local half of the served engine's
        `apply_actions`). Before any tick there is no step to record under.
        """

@typing.final
class Advisory:
    r"""
    One non-fatal adapter advisory: a message plus a severity tier.
    
    `severity` is `"info"` for benign hints (an authoring nudge, an
    explicitly-requested lossy step) and `"caution"` when the adapter
    substituted or fabricated model-visible data (a role-rebound camera, a
    zero-filled frame) — the tier an eval harness may want to hard-fail on.
    `str(advisory)` is the message.
    """
    @property
    def severity(self) -> builtins.str:
        r"""
        The severity tier: `"info"` or `"caution"`.
        """
    @property
    def message(self) -> builtins.str:
        r"""
        The human-readable note.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class BuildInfo:
    r"""
    The identity of this build of the native core: package version, protocol
    generation, the workflow edition it advertises, and how that edition was
    spelled. Every field is fixed at compile time.
    """
    @property
    def version(self) -> builtins.str:
        r"""
        The `rlmesh` package version the native core was built as.
        """
    @property
    def protocol_generation(self) -> builtins.str:
        r"""
        The wire protocol generation this build speaks (`rlmesh-wire-v1`).
        """
    @property
    def workflow_edition(self) -> builtins.str:
        r"""
        The exact workflow edition spelling this build advertises: the sealed
        `YYYY.MM` base on a release, `YYYY.MM-<cohort>` on a prerelease or
        source build.
        """
    @property
    def workflow_edition_base(self) -> builtins.str:
        r"""
        The sealed `YYYY.MM` base of `workflow_edition`, the same on every build
        of the edition; what `current_workflow_edition()` returns.
        """
    @property
    def supported_workflow_editions(self) -> builtins.list[builtins.str]:
        r"""
        Every workflow edition this build can drive a session at, newest first:
        the retained list a served peer offers on `supported_workflow_editions`
        in its handshake, so a describe envelope advertises exactly what the
        handshake will.
        """
    @property
    def build_cohort(self) -> builtins.str:
        r"""
        The cohort that spells `workflow_edition`: `stable` on a sealed release,
        the prerelease version (`0.1.0-rc.12`) on a prerelease, `dev.<git>` on a
        source build.
        """
    @property
    def build_source(self) -> builtins.str:
        r"""
        Where the cohort came from: `release` (a release build), `package` (a
        published crate or a checkout without git), or `git` (a source build
        stamped from its commit).
        """
    @property
    def git(self) -> typing.Optional[builtins.str]:
        r"""
        The git state a source build was stamped from — the short commit sha,
        suffixed `.dirty.<fingerprint>` when the tree had uncommitted changes —
        or `None` when the build was not stamped from git.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class EnvContract:
    @property
    def id(self) -> builtins.str: ...
    @property
    def env(self) -> EnvContract: ...
    @property
    def spec(self) -> EnvContract: ...
    @property
    def render_mode(self) -> typing.Optional[builtins.str]: ...
    @property
    def num_envs(self) -> builtins.int: ...
    @property
    def metadata(self) -> dict[str, object] | None: ...
    @property
    def observation_space(self) -> SpaceSpec: ...
    @property
    def action_space(self) -> SpaceSpec: ...
    def to_dict(self) -> dict[str, object]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PyEnvClient:
    def __init__(self, address: str, *, connect_timeout_seconds: float | None = None, request_timeout_seconds: float | None = None, workflow_edition: str | None = None) -> None: ...
    def address(self) -> str: ...
    def env_id(self) -> str: ...
    def selected_workflow_edition(self) -> str: ...
    def session_offer(self) -> tuple[list[str], str | None]: ...
    def pin_workflow_edition(self, selected_workflow_edition: str) -> None: ...
    def handshake(self) -> EnvContract: ...
    def observation_space(self) -> Space: ...
    def action_space(self) -> Space: ...
    def reset(self, seeds: list[int] | None = None, options: dict[str, object] | None = None, *, timeout_seconds: float | None = None) -> tuple[Value, ResetInfo]: ...
    def step(self, actions: Value, *, timeout_seconds: float | None = None) -> tuple[Value, float, bool, bool, StepInfo]: ...
    def render(self, env_index: int = 0, *, timeout_seconds: float | None = None) -> Value | None: ...
    def close(self) -> None: ...
    def shutdown(self, reason: str = 'owner shutdown') -> bool: ...

@typing.final
class PyEnvServer:
    r"""
    Python wrapper for the RLMesh EnvService server.
    """
    @property
    def env_contract(self) -> EnvContract:
        r"""
        Get the environment contract served by this endpoint.
        """
    @property
    def spec(self) -> EnvContract:
        r"""
        Alias for env_contract.
        """
    def __new__(cls, env: typing.Any, address: typing.Optional[builtins.str] = None, *, options: typing.Optional[ServeOptions] = None, native_values: builtins.bool = ..., close_env_on_shutdown: builtins.bool = ...) -> PyEnvServer:
        r"""
        Create a new RLMesh environment server.
        # Arguments
        * `env` - Python gymnasium.Env object, or a list of them to serve as the
          lanes of one endpoint (`num_envs = len(list)`)
        * `address` - Optional bind address shortcut
        """
    def address(self) -> builtins.str:
        r"""
        Get the server address.
        """
    def serve(self) -> None:
        r"""
        Start serving (blocking).
        Releases the GIL while running so other Python threads can execute.
        The env stays on this thread: every reset/step/render/close runs here,
        so an env built on the main thread is driven from it.
        """
    def start(self) -> None:
        r"""
        Start serving on a background thread.
        """
    def wait(self, timeout: typing.Optional[builtins.float] = None) -> builtins.bool:
        r"""
        Wait for a background server to stop.
        """
    def shutdown(self) -> None:
        r"""
        Shutdown the server.
        """

@typing.final
class PyModel:
    def __init__(self, predict_fn: collections.abc.Callable[[Value], Value], configure_fn: collections.abc.Callable[[EnvContract], object] | None = None, on_episode_end: collections.abc.Callable[[str], None] | None = None, on_close: collections.abc.Callable[[], None] | None = None, predict_chunk_fn: collections.abc.Callable[[Value, int], Value] | None = None, predict_batch_fn: collections.abc.Callable[[list[Value], list[dict[str, typing.Any]]], list[Value]] | None = None, predict_chunk_batch_fn: collections.abc.Callable[[list[Value], int, list[dict[str, typing.Any]]], list[Value]] | None = None, allow_fusion: bool = True, native_chunk: int | None = None) -> None: ...
    def run_local(self, env_address: str, execution_horizon: int = 1, prefetch_lead: int = 0, workflow_edition: str | None = None) -> dict[str, typing.Any]: ...
    def run_local_for_episodes(self, env_address: str, episodes: int, execution_horizon: int = 1, seeds: list[int] | None = None, max_episode_steps: int | None = None, max_episode_seconds: float | None = None, close_env: bool = False, trial_index_base: int | None = None, prefetch_lead: int = 0, workflow_edition: str | None = None, hooks: object | None = None) -> dict[str, typing.Any]: ...
    def serve(self, address: str, options: ServeOptions | None = None) -> None: ...

@typing.final
class PyModelClient:
    r"""
    Client handle to a model (policy) server: the model-side mirror of
    `PyEnvClient`. Bound to one env contract (one route) for its lifetime; the
    Python layer creates one per `rlmesh.session(model, env)`.
    """
    def __init__(self, address: str, env_contract: EnvContract, execution_horizon: int = 1, *, connect_timeout_seconds: float | None = None, request_timeout_seconds: float | None = None, workflow_edition: str | None = None, env_offer: tuple[list[str], str | None] | None = None) -> None: ...
    def address(self) -> str: ...
    def env_id(self) -> str: ...
    def selected_workflow_edition(self) -> str: ...
    def observation_space(self) -> Space: ...
    def action_space(self) -> Space: ...
    def reset(self, seed: int | None = None) -> None: ...
    def predict(self, observation: Value) -> Value: ...
    def close(self) -> None: ...

@typing.final
class PyVectorEnvClient:
    def __init__(self, address: str, *, connect_timeout_seconds: float | None = None, request_timeout_seconds: float | None = None, workflow_edition: str | None = None) -> None: ...
    def address(self) -> str: ...
    def env_id(self) -> str: ...
    def selected_workflow_edition(self) -> str: ...
    def session_offer(self) -> tuple[list[str], str | None]: ...
    def pin_workflow_edition(self, selected_workflow_edition: str) -> None: ...
    def handshake(self) -> EnvContract: ...
    def observation_space(self) -> Space: ...
    def action_space(self) -> Space: ...
    def num_envs(self) -> int: ...
    def reset(self, seeds: list[int] | None = None, options: dict[str, object] | None = None, *, timeout_seconds: float | None = None) -> tuple[Value, ResetInfo]: ...
    def step(self, actions: object, *, timeout_seconds: float | None = None) -> tuple[Value, Value, Value, Value, StepInfo]: ...
    def render(self, env_index: int = 0, *, timeout_seconds: float | None = None) -> Value | None: ...
    def close(self) -> None: ...
    def shutdown(self, reason: str = 'owner shutdown') -> bool: ...

@typing.final
class PyVectorEnvServer:
    @property
    def env_contract(self) -> EnvContract: ...
    @property
    def spec(self) -> EnvContract: ...
    def __new__(cls, env: typing.Any, address: typing.Optional[builtins.str] = None, *, options: typing.Optional[ServeOptions] = None, native_values: builtins.bool = ..., close_env_on_shutdown: builtins.bool = ...) -> PyVectorEnvServer:
        r"""
        Create a new vectorized RLMesh environment server.
        # Arguments
        * `env` - Python gymnasium.vector.VectorEnv object
        * `address` - Optional bind address shortcut
        """
    def address(self) -> builtins.str: ...
    def serve(self) -> None: ...
    def start(self) -> None: ...
    def wait(self, timeout: typing.Optional[builtins.float] = None) -> builtins.bool: ...
    def shutdown(self) -> None: ...

@typing.final
class PyVideoWriter:
    r"""
    Native AV1 recorder: encodes HWC uint8 frames to an `.mp4` on a dedicated
    encoder thread (no ffmpeg), built by the Python recorder and fed one
    camera's frames per step. `write_frame` only copies the frame and queues
    it, so the eval loop overlaps env stepping with encoding.
    """
    def __new__(cls, path: builtins.str, width: builtins.int, height: builtins.int, fps: builtins.int = ..., quality: builtins.int = ...) -> PyVideoWriter: ...
    def write_frame(self, buf: builtins.bytes | builtins.bytearray | builtins.memoryview, width: builtins.int, height: builtins.int, channels: builtins.int) -> None:
        r"""
        Queue one contiguous HWC uint8 frame (`channels` = 1/3/4) for encoding.
        
        `buf` is any C-contiguous uint8 buffer (bytes, a flat memoryview, a
        numpy array) -- read through the buffer protocol, so the only Python-side
        copy is the one that hands the frame to the encoder thread. An encode
        failure surfaces on a later call (or at `finish`), never silently.
        """
    def finish(self) -> tuple[builtins.int, builtins.int, builtins.int]:
        r"""
        Drain the encoder and finalize the file; returns `(frame_count, width, height)`.
        """

@typing.final
class PyViewer:
    r"""
    Native debug viewer, built by the Python `Session` when `view=` is set and fed
    one decoded HWC uint8 frame (the selected camera) per step.
    """
    def __new__(cls, terminal: builtins.bool = ..., http_port: typing.Optional[builtins.int] = None, fps: builtins.int = ..., format: typing.Optional[builtins.str] = None, quality: builtins.int = ...) -> PyViewer: ...
    def set_sources(self, sources: typing.Sequence[builtins.str], default: builtins.int) -> None:
        r"""
        Declare the selectable camera labels and the initial selection index.
        """
    def selected_source(self) -> typing.Optional[builtins.str]:
        r"""
        The currently-selected source label (key thread or browser), or `None`.
        """
    def wants_frame(self) -> builtins.bool:
        r"""
        Whether the throttle would draw now — gate an expensive frame fetch on this.
        """
    def feed_frame(self, buf: typing.Sequence[builtins.int], width: builtins.int, height: builtins.int, channels: builtins.int) -> None:
        r"""
        Feed one contiguous HWC uint8 frame for the selected source.
        """
    def feed_hud(self, step: builtins.int, reward: builtins.float, outcome: builtins.str, *, model_ms: builtins.float = ..., env_ms: builtins.float = ..., sps: builtins.float = ..., elapsed_s: builtins.float = ..., episode: builtins.int = ..., episodes: builtins.int = ..., seed: builtins.int = ..., width: builtins.int = ..., height: builtins.int = ..., chunk_pos: builtins.int = ..., chunk_len: builtins.int = ...) -> None:
        r"""
        Update the HUD: step / cumulative reward / outcome (all computed by the caller)
        plus the optional debug metrics the Session measures — model & env step timing,
        eval throughput, episode elapsed, episode index/seed, action-chunk replay
        position, and the selected source's frame size. The viewer fills in its own draw
        fps; every metric defaults to a "not applicable" sentinel so old callers still work.
        """
    def should_quit(self) -> builtins.bool:
        r"""
        Whether the user asked to quit via the terminal (q / Esc / Ctrl-C). The eval
        polls this each step and stops, since raw mode swallows the real SIGINT.
        """
    def take_skip(self) -> builtins.bool:
        r"""
        Take (and clear) a pending "end this episode early" request (the `n` key or the
        `/skip` route). The eval polls this each step and truncates the episode -- a
        soft, non-failure advance, distinct from `should_quit` stopping the whole run.
        """
    def warnings(self) -> builtins.list[builtins.str]:
        r"""
        Setup warnings (a backend that failed to come up), surfaced once by Python.
        """
    def close(self) -> None:
        r"""
        Tear down the viewer (restores the terminal / stops the HTTP server).
        """

@typing.final
class ServeOptions:
    @property
    def allow_remote_shutdown(self) -> builtins.bool: ...
    @property
    def idle_timeout_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def drain_timeout_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def close_timeout_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def workflow_edition(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, allow_remote_shutdown: builtins.bool = ..., idle_timeout_seconds: typing.Optional[builtins.float] = None, drain_timeout_seconds: typing.Optional[builtins.float] = None, close_timeout_seconds: typing.Optional[builtins.float] = None, workflow_edition: typing.Optional[builtins.str] = None) -> ServeOptions: ...

@typing.final
class Space:
    @property
    def spec(self) -> SpaceSpec: ...
    @property
    def kind(self) -> builtins.str: ...
    @property
    def shape(self) -> builtins.list[builtins.int]: ...
    @property
    def dtype(self) -> builtins.str: ...
    def seed(self, seed: typing.Optional[builtins.int] = None) -> typing.Optional[builtins.int]: ...
    def sample(self) -> object: ...
    def contains(self, value: object) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpaceSpec:
    @property
    def kind(self) -> builtins.str: ...
    @property
    def shape(self) -> builtins.list[builtins.int]: ...
    @property
    def dtype(self) -> builtins.str: ...
    def _details(self) -> object: ...
    def _to_dict(self) -> dict[str, object]: ...
    def to_space(self) -> Space: ...
    def to_gym_space(self) -> object: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Tensor:
    @property
    def shape(self) -> builtins.list[builtins.int]: ...
    @property
    def dtype(self) -> builtins.str: ...
    @property
    def ndim(self) -> builtins.int: ...
    @property
    def size(self) -> builtins.int: ...
    @property
    def nbytes(self) -> builtins.int: ...
    @property
    def strides(self) -> builtins.list[builtins.int]:
        r"""
        Strides in bytes per dimension, C-order.
        """
    @property
    def device(self) -> builtins.str:
        r"""
        Device holding the tensor data. Always `"cpu"`.
        """
    @property
    def buffer(self) -> memoryview: ...
    def __buffer__(self, flags: builtins.int, /) -> memoryview: ...
    def __new__(cls, buffer: object, shape: typing.Sequence[builtins.int], dtype: builtins.str) -> Tensor: ...
    def is_contiguous(self) -> builtins.bool:
        r"""
        Whether the elements are laid out C-contiguously.
        """
    def reshape(self, shape: typing.Sequence[builtins.int]) -> Tensor:
        r"""
        A tensor with the same elements and a new shape. One dimension may
        be ``-1`` to infer its size from the element count. Shares the
        underlying data when this tensor is contiguous.
        """
    def copy(self) -> Tensor:
        r"""
        A deep copy backed by fresh storage.
        """
    def __dlpack__(self, *, stream: object | None = None, max_version: typing.Optional[tuple[builtins.int, builtins.int]] = None, dl_device: typing.Optional[tuple[builtins.int, builtins.int]] = None, copy: typing.Optional[builtins.bool] = None) -> object:
        r"""
        Export the tensor as a DLPack capsule.
        
        With `max_version` of `(1, 0)` or newer the capsule is a DLPack 1.0
        `DLManagedTensorVersioned` flagged read-only; otherwise it is a
        legacy `DLManagedTensor`. `copy=True` exports a fresh writable
        buffer. Only `stream=None` and CPU `dl_device` are accepted.
        """
    def __dlpack_device__(self) -> tuple[builtins.int, builtins.int]:
        r"""
        DLPack device of the tensor data: `(kDLCPU, 0)`.
        """
    @staticmethod
    def from_dlpack(obj: object) -> Tensor:
        r"""
        Import a tensor from a DLPack capsule or any object implementing
        `__dlpack__`. Accepts both legacy and versioned capsules; the
        elements are always copied into fresh storage and the source
        capsule is consumed.
        """
    def tobytes(self) -> bytes: ...
    def __repr__(self) -> builtins.str: ...

def _set_python_peer_info(*, language: str | None = None, language_version: str | None = None, package_version: str | None = None, os: str | None = None, os_version: str | None = None, arch: str | None = None, framework_versions: dict[str, str] | None = None, extra: dict[str, str] | None = None) -> None: ...

def adapters_join_check(env_tags_json: str, observation_space: object, action_space: object) -> list[Advisory]: ...

def adapters_resolve(env_tags_json: str, observation_space: object, action_space: object, model_spec_json: str) -> AdapterPlan: ...

def adapters_spec_normalize(side: str, spec_json: str, allow_custom: bool, role_policy: str = 'passthrough', require_frames: bool = False, require_labels: bool = False) -> str: ...

def box_space_spec(low: int | float, high: int | float, shape: list[int], dtype: str | None = None) -> SpaceSpec: ...

def build_info() -> BuildInfo:
    r"""
    This build's identity: the package version, the protocol generation, and
    the workflow edition it advertises with the cohort behind that spelling.
    """

def current_workflow_edition() -> builtins.str:
    r"""
    The bare `YYYY.MM` workflow edition this build runs at — the value to paste
    into a declaration, on every build.
    
    A declaration names the contract a participant was authored against, and a
    bare base selects whichever spelling of that base both sides offer: the
    sealed name on a release, this build's cohort (`YYYY.MM-<cohort>`, what
    `rlmesh.build_info().workflow_edition` reports) on a prerelease or local
    build. That cohort spelling is also accepted as a declaration, pinning to
    that exact moving build.
    """

def describe_envelope_normalize(kind: str, pieces_json: str, generated_at: str | None = None) -> str: ...

def dict_space_spec(entries: dict[str, object]) -> SpaceSpec: ...

def discrete_space_spec(n: int, start: int = 0, dtype: str | None = None) -> SpaceSpec: ...

def multi_binary_space_spec(shape: list[int], dtype: str | None = None) -> SpaceSpec: ...

def multi_discrete_space_spec(nvec: list[int], dtype: str | None = None) -> SpaceSpec: ...

def predict_seed(episode_seed: int, predict_index: int) -> int: ...

def run_cli(args: list[str]) -> int: ...

def sandbox_reap_orphans() -> None: ...

def sandbox_start_env(source: str, *, base_image: str | None = None, rlmesh_package: str | None = None, packages: list[str] | None = None, imports: list[str] | None = None, kwargs_json: str | None = None, num_envs: int = 1, vectorization_mode: str | None = None, trust_remote_code: bool = False, allow_unpinned_hf: bool = False, build_memory: str | None = None) -> SandboxRunInfo: ...

def sandbox_stop_env(*, container_id: str) -> None: ...

def space_spec_from_gym_space(space: object) -> SpaceSpec: ...

def text_space_spec(max_length: int, min_length: int = 1, charset: str | None = None) -> SpaceSpec: ...

def tuple_space_spec(spaces: list[object]) -> SpaceSpec: ...

def validate_workflow_edition(edition: builtins.str) -> builtins.str:
    r"""
    Refuse a declared workflow edition this build cannot run a session at, naming
    the value and the editions it offers; return it trimmed otherwise.
    
    The single Python-side boundary for a declared edition: every surface that
    takes one from a user (`ServeOptions`, `--workflow-edition`, `run`/`session`,
    `RLMESH_WORKFLOW_EDITION`, a class declaration, `[tool.rlmesh]`) resolves
    through it, so a name that cannot work is refused where it is typed rather
    than as a negotiation failure on the first connection.
    """

