# This file is automatically generated by pyo3_stub_gen
# ruff: noqa

import builtins
import collections.abc
import typing
from typing import TypeAlias, TypedDict
__all__ = [
    "RLMeshException",
    "ProtocolException",
    "EnvironmentException",
    "ACTION_DELTA_POS",
    "ACTION_DELTA_POS_2",
    "ACTION_DELTA_ROT",
    "ACTION_DELTA_ROT_2",
    "ACTION_GRIPPER",
    "ACTION_GRIPPER_2",
    "AdapterPlan",
    "EEF_POS",
    "EEF_POS_2",
    "EEF_ROT",
    "EEF_ROT_2",
    "ENV_METADATA_KEY",
    "EnvContract",
    "GRIPPER_POS",
    "GRIPPER_POS_2",
    "IMAGE_LAYOUTS",
    "IMAGE_PRIMARY",
    "IMAGE_SECONDARY",
    "IMAGE_WRIST",
    "INSTRUCTION",
    "JOINT_POS",
    "JOINT_VEL",
    "MODEL_METADATA_KEY",
    "PrimitiveValue",
    "PyEnvClient",
    "PyEnvServer",
    "PyModel",
    "PyModelClient",
    "PyVectorEnvClient",
    "PyVectorEnvServer",
    "ROTATION_DIMS",
    "ServeOptions",
    "Space",
    "SpaceSpec",
    "Tensor",
    "Value",
    "adapters_join_check",
    "adapters_resolve",
    "adapters_spec_normalize",
    "box_space_spec",
    "dict_space_spec",
    "discrete_space_spec",
    "multi_binary_space_spec",
    "multi_discrete_space_spec",
    "run_cli",
    "sandbox_reap_orphans",
    "sandbox_start_env",
    "sandbox_stop_env",
    "space_spec_from_gym_space",
    "text_space_spec",
    "tuple_space_spec",
]

PrimitiveValue: TypeAlias = None | bool | int | float | str | bytes
Value: TypeAlias = PrimitiveValue | Tensor | list["Value"] | tuple["Value", ...] | dict[str, "Value"]
ACTION_DELTA_POS: builtins.str
ACTION_DELTA_POS_2: builtins.str
ACTION_DELTA_ROT: builtins.str
ACTION_DELTA_ROT_2: builtins.str
ACTION_GRIPPER: builtins.str
ACTION_GRIPPER_2: builtins.str
EEF_POS: builtins.str
EEF_POS_2: builtins.str
EEF_ROT: builtins.str
EEF_ROT_2: builtins.str
ENV_METADATA_KEY: builtins.str
GRIPPER_POS: builtins.str
GRIPPER_POS_2: builtins.str
IMAGE_LAYOUTS: builtins.list[builtins.str]
IMAGE_PRIMARY: builtins.str
IMAGE_SECONDARY: builtins.str
IMAGE_WRIST: builtins.str
INSTRUCTION: builtins.str
JOINT_POS: builtins.str
JOINT_VEL: builtins.str
MODEL_METADATA_KEY: builtins.str
ROTATION_DIMS: builtins.dict[builtins.str, builtins.int]
__version__: builtins.str

class RLMeshException(builtins.RuntimeError): ...

class ProtocolException(RLMeshException): ...

class EnvironmentException(RLMeshException): ...

ResetInfo: TypeAlias = dict[str, object]

StepInfo: TypeAlias = dict[str, object]

class SandboxRunInfo(TypedDict):
    requested_source: str
    resolved_source: str
    address: str
    container_id: str

class SandboxBuildInfo(TypedDict):
    requested_source: str
    resolved_source: str
    image: str
    alias: str | None
    image_id: str

@typing.final
class AdapterPlan:
    r"""
    A resolved adapter plan handle backed by the `rlmesh-adapters` core.
    """
    def describe(self) -> builtins.str:
        r"""
        Human-readable summary of the resolved transformations.
        """
    def referenced_obs_keys(self) -> builtins.list[builtins.str]:
        r"""
        The top-level observation keys this adapter reads.
        
        A host wrapper should encode only these before calling
        [`transform_obs`](Self::transform_obs), so an unused — possibly
        unencodable — observation key never aborts a step.
        """
    def custom_inputs(self) -> builtins.list[tuple[builtins.str, builtins.str]]:
        r"""
        `(model_key, transform)` pairs for custom-input holes, plan order.
        """
    def transform_obs(self, raw_obs: typing.Any) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Apply the observation plans to a canonical value-tree observation map.
        
        Returns `{model_key: encoded_value}`; custom inputs are omitted
        (the caller fills them from the raw host observation).
        """
    def transform_action(self, raw_action: typing.Any) -> typing.Any:
        r"""
        Apply the action plan to a canonical value-tree model action.
        """

@typing.final
class EnvContract:
    @property
    def id(self) -> builtins.str: ...
    @property
    def env(self) -> EnvContract: ...
    @property
    def spec(self) -> EnvContract: ...
    @property
    def render_mode(self) -> typing.Optional[builtins.str]: ...
    @property
    def num_envs(self) -> builtins.int: ...
    @property
    def metadata(self) -> dict[str, object] | None: ...
    @property
    def observation_space(self) -> SpaceSpec: ...
    @property
    def action_space(self) -> SpaceSpec: ...
    def to_dict(self) -> dict[str, object]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PyEnvClient:
    def __init__(self, address: str, *, connect_timeout_seconds: float | None = None, request_timeout_seconds: float | None = None) -> None: ...
    def address(self) -> str: ...
    def handshake(self) -> EnvContract: ...
    def observation_space(self) -> Space: ...
    def action_space(self) -> Space: ...
    def reset(self, seeds: list[int] | None = None, options: dict[str, object] | None = None, *, timeout_seconds: float | None = None) -> tuple[Value, ResetInfo]: ...
    def step(self, actions: Value, *, timeout_seconds: float | None = None) -> tuple[Value, float, bool, bool, StepInfo]: ...
    def render(self, env_index: int = 0, *, timeout_seconds: float | None = None) -> Value | None: ...
    def close(self) -> None: ...
    def shutdown(self, reason: str = 'owner shutdown') -> bool: ...

@typing.final
class PyEnvServer:
    r"""
    Python wrapper for the RLMesh EnvService server.
    """
    @property
    def env_contract(self) -> EnvContract:
        r"""
        Get the environment contract served by this endpoint.
        """
    @property
    def spec(self) -> EnvContract:
        r"""
        Alias for env_contract.
        """
    def __new__(cls, env: typing.Any, address: typing.Optional[builtins.str] = None, *, options: typing.Optional[ServeOptions] = None) -> PyEnvServer:
        r"""
        Create a new RLMesh environment server.
        # Arguments
        * `env` - Python gymnasium.Env object
        * `address` - Optional bind address shortcut
        """
    def address(self) -> builtins.str:
        r"""
        Get the server address.
        """
    def serve(self) -> None:
        r"""
        Start serving (blocking).
        Releases the GIL while running so other Python threads can execute.
        """
    def start(self) -> None:
        r"""
        Start serving on a background thread.
        """
    def wait(self, timeout: typing.Optional[builtins.float] = None) -> builtins.bool:
        r"""
        Wait for a background server to stop.
        """
    def shutdown(self) -> None:
        r"""
        Shutdown the server.
        """

@typing.final
class PyModel:
    def __init__(self, predict_fn: collections.abc.Callable[[Value, object], Value], configure_fn: collections.abc.Callable[[EnvContract], object] | None = None, on_reset: collections.abc.Callable[[], None] | None = None, on_episode_end: collections.abc.Callable[[], None] | None = None, on_close: collections.abc.Callable[[], None] | None = None) -> None: ...
    def run_local(self, env_address: str, token: str) -> None: ...
    def run_local_for_episodes(self, env_address: str, token: str, max_episodes: int) -> None: ...
    def serve(self, address: str, token: str, options: ServeOptions | None = None) -> None: ...

@typing.final
class PyModelClient:
    r"""
    Client handle to a model (policy) server: the model-side mirror of
    `PyEnvClient`. Bound to one env contract (one route) for its lifetime; the
    Python layer creates one per `RemoteModel.against(env)`.
    """
    def __init__(self, address: str, env_contract: EnvContract, token: str = '') -> None: ...
    def address(self) -> str: ...
    def observation_space(self) -> Space: ...
    def action_space(self) -> Space: ...
    def reset(self) -> None: ...
    def predict(self, observation: Value) -> Value: ...
    def close(self) -> None: ...

@typing.final
class PyVectorEnvClient:
    def __init__(self, address: str, *, connect_timeout_seconds: float | None = None, request_timeout_seconds: float | None = None) -> None: ...
    def address(self) -> str: ...
    def handshake(self) -> EnvContract: ...
    def observation_space(self) -> Space: ...
    def action_space(self) -> Space: ...
    def num_envs(self) -> int: ...
    def reset(self, seeds: list[int] | None = None, options: dict[str, object] | None = None, *, timeout_seconds: float | None = None) -> tuple[Value, ResetInfo]: ...
    def step(self, actions: object, *, timeout_seconds: float | None = None) -> tuple[Value, Value, Value, Value, StepInfo]: ...
    def render(self, env_index: int = 0, *, timeout_seconds: float | None = None) -> Value | None: ...
    def close(self) -> None: ...
    def shutdown(self, reason: str = 'owner shutdown') -> bool: ...

@typing.final
class PyVectorEnvServer:
    @property
    def env_contract(self) -> EnvContract: ...
    @property
    def spec(self) -> EnvContract: ...
    def __new__(cls, env: typing.Any, address: typing.Optional[builtins.str] = None, *, options: typing.Optional[ServeOptions] = None) -> PyVectorEnvServer:
        r"""
        Create a new vectorized RLMesh environment server.
        # Arguments
        * `env` - Python gymnasium.vector.VectorEnv object
        * `address` - Optional bind address shortcut
        """
    def address(self) -> builtins.str: ...
    def serve(self) -> None: ...
    def start(self) -> None: ...
    def wait(self, timeout: typing.Optional[builtins.float] = None) -> builtins.bool: ...
    def shutdown(self) -> None: ...

@typing.final
class ServeOptions:
    @property
    def allow_remote_shutdown(self) -> builtins.bool: ...
    @property
    def idle_timeout_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def drain_timeout_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def close_timeout_seconds(self) -> typing.Optional[builtins.float]: ...
    @property
    def token(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, *, allow_remote_shutdown: builtins.bool = ..., idle_timeout_seconds: typing.Optional[builtins.float] = None, drain_timeout_seconds: typing.Optional[builtins.float] = None, close_timeout_seconds: typing.Optional[builtins.float] = None, token: typing.Optional[builtins.str] = None) -> ServeOptions: ...

@typing.final
class Space:
    @property
    def spec(self) -> SpaceSpec: ...
    @property
    def kind(self) -> builtins.str: ...
    @property
    def shape(self) -> builtins.list[builtins.int]: ...
    @property
    def dtype(self) -> builtins.str: ...
    def seed(self, seed: typing.Optional[builtins.int] = None) -> typing.Optional[builtins.int]: ...
    def sample(self) -> object: ...
    def contains(self, value: object) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpaceSpec:
    @property
    def kind(self) -> builtins.str: ...
    @property
    def shape(self) -> builtins.list[builtins.int]: ...
    @property
    def dtype(self) -> builtins.str: ...
    def _details(self) -> object: ...
    def _to_dict(self) -> dict[str, object]: ...
    def to_space(self) -> Space: ...
    def to_gym_space(self) -> object: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Tensor:
    @property
    def shape(self) -> builtins.list[builtins.int]: ...
    @property
    def dtype(self) -> builtins.str: ...
    @property
    def ndim(self) -> builtins.int: ...
    @property
    def size(self) -> builtins.int: ...
    @property
    def nbytes(self) -> builtins.int: ...
    @property
    def strides(self) -> builtins.list[builtins.int]:
        r"""
        Strides in bytes per dimension, C-order.
        """
    @property
    def device(self) -> builtins.str:
        r"""
        Device holding the tensor data. Always `"cpu"`.
        """
    @property
    def buffer(self) -> memoryview: ...
    def __buffer__(self, flags: builtins.int, /) -> memoryview: ...
    def __new__(cls, buffer: object, shape: typing.Sequence[builtins.int], dtype: builtins.str) -> Tensor: ...
    def is_contiguous(self) -> builtins.bool:
        r"""
        Whether the elements are laid out C-contiguously.
        """
    def reshape(self, shape: typing.Sequence[builtins.int]) -> Tensor:
        r"""
        A tensor with the same elements and a new shape. One dimension may
        be ``-1`` to infer its size from the element count. Shares the
        underlying data when this tensor is contiguous.
        """
    def copy(self) -> Tensor:
        r"""
        A deep copy backed by fresh storage.
        """
    def __dlpack__(self, *, stream: object | None = None, max_version: typing.Optional[tuple[builtins.int, builtins.int]] = None, dl_device: typing.Optional[tuple[builtins.int, builtins.int]] = None, copy: typing.Optional[builtins.bool] = None) -> object:
        r"""
        Export the tensor as a DLPack capsule.
        
        With `max_version` of `(1, 0)` or newer the capsule is a DLPack 1.0
        `DLManagedTensorVersioned` flagged read-only; otherwise it is a
        legacy `DLManagedTensor`. `copy=True` exports a fresh writable
        buffer. Only `stream=None` and CPU `dl_device` are accepted.
        """
    def __dlpack_device__(self) -> tuple[builtins.int, builtins.int]:
        r"""
        DLPack device of the tensor data: `(kDLCPU, 0)`.
        """
    @staticmethod
    def from_dlpack(obj: object) -> Tensor:
        r"""
        Import a tensor from a DLPack capsule or any object implementing
        `__dlpack__`. Accepts both legacy and versioned capsules; the
        elements are always copied into fresh storage and the source
        capsule is consumed.
        """
    def tobytes(self) -> bytes: ...
    def __repr__(self) -> builtins.str: ...

def _set_python_peer_info(*, language: str | None = None, language_version: str | None = None, package_version: str | None = None, os: str | None = None, os_version: str | None = None, arch: str | None = None, framework_versions: dict[str, str] | None = None) -> None: ...

def adapters_join_check(env_tags_json: str, observation_space: object, action_space: object) -> None: ...

def adapters_resolve(env_tags_json: str, observation_space: object, action_space: object, model_spec_json: str) -> AdapterPlan: ...

def adapters_spec_normalize(side: str, spec_json: str, allow_custom: bool) -> str: ...

def box_space_spec(low: float, high: float, shape: list[int], dtype: str | None = None) -> SpaceSpec: ...

def dict_space_spec(entries: dict[str, object]) -> SpaceSpec: ...

def discrete_space_spec(n: int, start: int = 0, dtype: str | None = None) -> SpaceSpec: ...

def multi_binary_space_spec(shape: list[int], dtype: str | None = None) -> SpaceSpec: ...

def multi_discrete_space_spec(nvec: list[int], dtype: str | None = None) -> SpaceSpec: ...

def run_cli(args: list[str]) -> int: ...

def sandbox_reap_orphans() -> None: ...

def sandbox_start_env(source: str, *, base_image: str | None = None, rlmesh_package: str | None = None, packages: list[str] | None = None, imports: list[str] | None = None, kwargs_json: str | None = None, num_envs: int = 1, vectorization_mode: str | None = None, trust_remote_code: bool = False, allow_unpinned_hf: bool = False, build_memory: str | None = None) -> SandboxRunInfo: ...

def sandbox_stop_env(*, container_id: str) -> None: ...

def space_spec_from_gym_space(space: object) -> SpaceSpec: ...

def text_space_spec(max_length: int, min_length: int = 1, charset: str | None = None) -> SpaceSpec: ...

def tuple_space_spec(spaces: list[object]) -> SpaceSpec: ...

